# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taplists', '0004_auto_20160407_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='region',
            field=models.CharField(default=b'Farmville', max_length=200),
        ),
    ]
