# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taplists', '0005_style_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bar',
            options={'ordering': ('bar', 'region')},
        ),
        migrations.RemoveField(
            model_name='style',
            name='region',
        ),
        migrations.AddField(
            model_name='bar',
            name='region',
            field=models.CharField(default=b'Farmville', max_length=200),
        ),
    ]
