# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taplists', '0006_auto_20160409_0000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bar',
            options={'ordering': ('barname', 'region')},
        ),
        migrations.RenameField(
            model_name='bar',
            old_name='bar',
            new_name='barname',
        ),
    ]
