# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 01:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taplists', '0007_auto_20160409_0019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bar',
            options={'ordering': ('bar',)},
        ),
        migrations.RenameField(
            model_name='bar',
            old_name='barname',
            new_name='bar',
        ),
        migrations.RemoveField(
            model_name='bar',
            name='region',
        ),
    ]
