# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taplists', '0008_auto_20160409_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='region',
            field=models.CharField(default=b'Farmville', max_length=200),
        ),
    ]
