# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 02:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taplists', '0009_bar_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bar',
            options={'ordering': ('bar', 'region')},
        ),
    ]
